base: 'https://t3exchange-v13.ddev.site/'
baseVariants:
  - base: 'https://t3exchange-v13-testing.ddev.site/'
    condition: 'applicationContext == "Testing"'
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
routes: {  }
