name: t3exchange-v13
type: typo3
docroot: public
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames:
    - t3exchange-v13-testing
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment:
    - TYPO3_CONTEXT=Development
    - TYPO3_EXCHANGE_CONFIG=/var/www/html/.peer-config.json
nodejs_version: "24"
corepack_enable: false
